---
name: climate_shocks
channels: 
  - plotly
  - conda-forge
  - defaults
dependencies:
  - conda-lock=1.4.0
  - ipykernel=6.21.2
  - jupyterlab=3.6.1
  - matplotlib=3.7.0
  - pandas
  - pip >=21.1
  - plotly>=5.13.0
  - pre-commit=3.1.1
  - pytask-latex>=0.4.0
  - pytask-parallel>=0.4.0
  - pytask>=0.4.0
  - pytest=7.2.2
  - pytest-cov=4.0.0
  - pytest-xdist=3.2.0
  - python-graphviz=0.20.1
  - pyyaml=6.0
  - seaborn=0.12.2
  - scikit-learn=1.2.1
  - scipy
  - setuptools_scm=7.1.0
  - statsmodels=0.13.5
  - toml=0.10.2
  - tox-conda=0.10.2

  - pip: [-e ., kaleido]




  

  